substitutions:
  MODBUS_READ_FUNCTION: "0x43"


uart:
  - id: ${device}_uart
    rx_pin: ${rx_pin}
    tx_pin: ${tx_pin}
    baud_rate: 38400
    stop_bits: 1
    
modbus:
    - id: ${device}_modbus
      uart_id: ${device}_uart
      #send_wait_time: 10ms

 
modbus_controller:
  id: ${device}_ahc9000_modbus_controller
  address: 1
  modbus_id: ${device}_modbus
  update_interval: 60s
  command_throttle: 10ms
  
.channel_02_current_temp_custom_command: &channel_02_current_temp_custom_command
  - 0x1
  - 0x43
  - 0x1
  - 0x4
  - 0x1
  - 0x7
