external_components:
  - source: 
      type: git
      url: https://github.com/heinekmadsen/esphome_components
      ref: dev
    refresh: 0s
    components: [wavinahc9000v2]

  # PR required until merged into main
  #- source: github://pr#3295
  #  components: [modbus_controller]
  #  refresh: 0s

wavinahc9000v2:
